definitions:
  health.HealthResponse:
    properties:
      data: {}
      error_msg:
        type: string
    type: object
  oauth.BasicUserInfo:
    properties:
      avatar_url:
        type: string
      id:
        type: integer
      nickname:
        type: string
      trust_level:
        $ref: '#/definitions/oauth.TrustLevel'
      username:
        type: string
    type: object
  oauth.CallbackRequest:
    properties:
      code:
        type: string
      state:
        type: string
    type: object
  oauth.CallbackResponse:
    properties:
      data: {}
      error_msg:
        type: string
    type: object
  oauth.GetLoginURLResponse:
    properties:
      data:
        type: string
      error_msg:
        type: string
    type: object
  oauth.LogoutResponse:
    properties:
      data: {}
      error_msg:
        type: string
    type: object
  oauth.TrustLevel:
    enum:
    - 0
    - 1
    - 2
    - 3
    - 4
    type: integer
    x-enum-varnames:
    - TrustLevelNewUser
    - TrustLevelBasicUser
    - TrustLevelUser
    - TrustLevelActiveUser
    - TrustLevelLeader
  oauth.UserInfoResponse:
    properties:
      data:
        $ref: '#/definitions/oauth.BasicUserInfo'
      error_msg:
        type: string
    type: object
info:
  contact: {}
  title: Linux Do CDK
  version: 0.1.0
paths:
  /api/v1/health:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/health.HealthResponse'
      tags:
      - health
  /api/v1/oauth/callback:
    post:
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/oauth.CallbackRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/oauth.CallbackResponse'
      tags:
      - oauth
  /api/v1/oauth/login:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/oauth.GetLoginURLResponse'
      tags:
      - oauth
  /api/v1/oauth/logout:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/oauth.LogoutResponse'
      tags:
      - oauth
  /api/v1/oauth/user-info:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/oauth.UserInfoResponse'
      tags:
      - oauth
swagger: "2.0"
